### ISSUE TITLE
Improve Github Pages

### ISSUE THREAD

**Issue by tuur29** [tuur29/fuzzyclock#60]
- [x] Set custom colors
- [x] Fix `&rightarrow;` not rendering
- [x] Hide table borders?
- [x] Add table of contents
- [x] Add bunch of download buttons at top?
- [x] Capitalize repo title
- [x] Add image previews like on Google Play store
