### ISSUE TITLE
Write READMEs

### ISSUE THREAD

**Issue by tuur29** [tuur29/fuzzyclock#7]
- [x] Mention minimum required android version
- [x] Invite translation PR's?
- [x] Write explanation
- [x] Mention setting Android studio configuration to Nothing
- [x] Prepare links to Google Play
